name: wernerharing
favicon: null
layout_spectrum: 1
typography_spectrum: 0.69458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0.75
  lightness: 0.6715713860467076
  saturation: 0.7318161320872605
  rhythmicContrast: 0.5792220481671393
purpose: []
